//! The read side: sessions and turns, as a client browses them.
//!
//! One structure, fed two ways. The live server folds events into it as they
//! happen; `luu export` folds a recorded file into it. That is deliberate — a
//! static mirror of this API that was generated by different code than the
//! server would drift, and the day it drifts it lies about the thing it exists
//! to stand in for.

use serde::{Deserialize, Serialize};

use crate::backend::Usage;
use crate::context::{
    Counter, Diverged, Evicted, Prune, Pruned, Repeat, Repeated, Results, Superseded,
};
use crate::job::{ApprovedBy, ClosedBy, JobId, JobState, Plan, PlanSource, Replaced};
use crate::protocol::{Grounding, Refusal, ServerMessage, TurnId};
use crate::record::{self, RecordLine};
use crate::sandbox::Verdict;
use crate::trace::{Bucket, TraceMessage};
use crate::turn::EndReason;

/// How the context was spent on one turn, as we measured it before the call.
/// `usage` on the same turn is the backend's own count afterwards; the two
/// differ by the chat template we never see, and that difference is a reading,
/// not an error.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Budget {
    /// `None` when the model's window is unknown.
    pub limit: Option<u32>,
    pub counter: Counter,
    pub buckets: Vec<Bucket>,
}

/// How much of this turn's prompt the previous one already contained. `None`
/// on the first turn of a session, where there is nothing to compare against.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct PrefixReuse {
    pub shared_bytes: usize,
    pub shared_tokens: u32,
    pub prompt_tokens: u32,
}

/// One model call a turn made *after* its first.
///
/// A turn that uses a tool is several calls, and the backend's
/// `usage.prompt_tokens` is summed over all of them. Without these the panel
/// compares our count of one call against the backend's count of three, and
/// presents the difference as chat-template overhead. See
/// `RECORD/2026-08-27.the-m4-pro-run.completed.md`, which is where a 1 962-token gap
/// turned out to be this.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExtraCall {
    /// Counts from 1 within the turn, so these start at 2.
    pub step: u32,
    pub prompt_tokens: u32,
    pub shared_bytes: usize,
    pub shared_tokens: u32,
}

/// One tool call as a client browses it — the "tool call timeline" panel the
/// design asks for, which is arguments, verdict, duration and result size.
///
/// The result half is optional because a call that was made and has not come
/// back yet is a real state, and a panel that waits for both would show nothing
/// while a command runs.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCallView {
    pub step: u32,
    pub name: String,
    pub arguments: serde_json::Value,
    /// Allowed or denied, and *which rule* matched — plus who enforced it.
    pub verdict: Option<Verdict>,
    pub error: Option<String>,
    pub output: String,
    pub truncated: bool,
    pub duration_ms: Option<u64>,
    /// What the subprocess did, where there was one. `None` for an in-process
    /// tool and for a recording made before the field existed.
    #[serde(default)]
    pub command: Option<crate::tools::CommandResult>,
}

/// One job as a client browses it. The transcript groups by this, which is
/// the point: the view collapses exactly what the context collapses.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JobView {
    pub id: JobId,
    pub objective: String,
    /// The plan it is held to, or `None` while it is a draft — a job whose
    /// objective is known and whose plan is not.
    ///
    /// `None` is never read as *no restriction*: nothing narrows a sandbox from
    /// this field. See [`crate::job::Job::plan`], where the argument lives.
    #[serde(default)]
    pub plan: Option<Plan>,
    /// The plan as it was *proposed*, kept beside the one above because the
    /// difference between them is the cost of the gate.
    #[serde(default)]
    pub proposed: Option<Plan>,
    /// Whether a planning call produced the proposal, or answered in prose.
    #[serde(default)]
    pub source: Option<PlanSource>,
    pub state: JobState,
    /// What its turns are sent as once it is closed. The summary text only.
    pub summary: Option<String>,
    /// Which authority closed it, beside what the close produced.
    #[serde(default)]
    pub closed_by: Option<ClosedBy>,
    /// Which authority approved it: the operator at the gate, or a key that
    /// signed. Absent until it is approved, and in a view folded from a
    /// recording made before signatures existed.
    #[serde(default)]
    pub approved_by: Option<ApprovedBy>,
    /// What the fold took out of the prompt, and what it was worth there —
    /// counted at the close, because it is only true then. Absent while the job
    /// is open, and in a view folded from a recording made before format 9. See
    /// `RECORD/2026-09-08.what-a-fold-writes-down.completed.md`.
    #[serde(default)]
    pub replaced: Option<Replaced>,
}

pub type TaskView = JobView;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TurnView {
    pub turn: TurnId,
    /// The job it was asked inside, when there was one.
    #[serde(default, alias = "task")]
    pub job: Option<JobId>,
    /// What the user asked.
    pub prompt: String,
    /// What the model produced, assembled. Partial on a cancel or a failure.
    pub text: String,
    pub reason: Option<EndReason>,
    pub usage: Option<Usage>,
    pub error: Option<String>,
    /// The exact string handed to the model — the trace channel's, not a
    /// reconstruction. `None` when the turn was recorded without `--trace`.
    pub prompt_sent: Option<String>,
    pub budget: Option<Budget>,
    /// What the prompt cache could reuse of the previous turn's prompt.
    pub prefix: Option<PrefixReuse>,
    /// The round trips after the first, when the turn used a tool. `budget` and
    /// `prefix` describe the first call only, so a client that adds these up is
    /// the only one whose total matches `usage`.
    #[serde(default)]
    pub extra_calls: Vec<ExtraCall>,
    /// What the agent did during the turn, in order.
    #[serde(default)]
    pub tools: Vec<ToolCallView>,
    /// What this turn's selection dropped from the window, when it dropped
    /// anything. Beside the budget rather than inside it: the buckets say what
    /// the prompt is worth, this says what stopped being in it.
    #[serde(default)]
    pub dropped: Option<Evicted>,
    /// The turn whose selection dropped *this* one. The transcript keeps an
    /// evicted turn and marks it — removing it would make the view agree with
    /// the prompt and lose the difference between them, which is the one thing
    /// a debug client is for.
    #[serde(default)]
    pub evicted_by: Option<TurnId>,
    /// What this turn's selection pruned, when it pruned anything: the turns
    /// that gave up their spans so that none of them had to be dropped whole.
    #[serde(default)]
    pub cited: Option<Pruned>,
    /// The turn whose selection took *this* one's code out of the prompt. The
    /// transcript keeps what was attached — the difference between the
    /// transcript and the prompt is the one thing a debug client is for, and
    /// this is the other half of it.
    #[serde(default)]
    pub pruned_by: Option<TurnId>,
    /// The spans this turn was asked with, by reference — the specs, never the
    /// bytes.
    ///
    /// It is what makes a resume able to read them again instead of losing
    /// them, and it is the first thing in this view that says a turn carried
    /// code at all: `prompt_sent` has the bytes fused into it and nothing took
    /// them apart. Empty on a turn that carried none, and on every turn of
    /// every stream written before protocol 6. See
    /// `RECORD/2026-09-19.fragments-by-reference.completed.md`.
    #[serde(default)]
    pub code: Vec<Grounding>,
    /// What rule A kept out of this turn's render: spans a turn owns and did
    /// not send, because something else in the same prompt already shows them.
    ///
    /// `None` on every turn of every stream written before `record::FORMAT` 14,
    /// and on every turn rendered under `Repeat::Always` — which are two
    /// different claims, and the format number is what tells them apart. See
    /// `RECORD/2026-09-19.one-counting-surface.completed.md`.
    #[serde(default)]
    pub repeated: Option<Repeated>,
    /// Paths this turn's prompt sent under more than one body — the same file,
    /// twice, with different contents.
    ///
    /// The other side of the sentence above: here the transcript and the prompt
    /// do not merely differ, the prompt disagrees with *itself*. Empty on every
    /// turn of a session that never edits a file it has quoted, which is every
    /// recording made before `RECORD/2026-09-19.one-path-two-bodies.completed.md`.
    #[serde(default)]
    pub diverged: Vec<Diverged>,
    /// Paths this turn's prompt sent a stale body for as a citation rather than
    /// as bytes, because a later turn had read the same span differently.
    ///
    /// The repair of the field above, and read with it: under `Repeat::Once`
    /// these two are never both non-empty about the same path, because
    /// replacing the stale body is what leaves the render one body to send.
    /// Empty on every turn of every stream written before `record::FORMAT` 15,
    /// and on every turn rendered under `Repeat::Always` — which are two
    /// different claims, and the format number is what tells them apart. See
    /// `RECORD/2026-09-20.the-newest-body-wins.completed.md`.
    #[serde(default)]
    pub superseded: Vec<Superseded>,
    pub started_at_ms: u64,
    pub ended_at_ms: Option<u64>,
}

impl TurnView {
    fn new(turn: TurnId, job: Option<JobId>, prompt: String, started_at_ms: u64) -> Self {
        Self {
            turn,
            job,
            prompt,
            text: String::new(),
            reason: None,
            usage: None,
            error: None,
            prompt_sent: None,
            budget: None,
            prefix: None,
            extra_calls: Vec::new(),
            tools: Vec::new(),
            dropped: None,
            evicted_by: None,
            cited: None,
            pruned_by: None,
            code: Vec::new(),
            repeated: None,
            diverged: Vec::new(),
            superseded: Vec::new(),
            started_at_ms,
            ended_at_ms: None,
        }
    }

    /// Backwards compatibility accessor for callers that called `turn.task`.
    pub fn task(&self) -> Option<JobId> {
        self.job
    }

    pub fn is_running(&self) -> bool {
        self.ended_at_ms.is_none()
    }
}

/// One thing the server declined to do.
///
/// Kept because something wanted to count them, which is the condition the fold
/// itself named when it started dropping them: *"it stays out of the view until
/// something wants to count them"*. The clause that survives is the other one —
/// *not session state* — and this does not make a refusal into a turn. It makes
/// it countable.
///
/// Additive to the view and **no format bump**: `refused` lines have been in
/// the record since format 4 and were widened by format 7, so every recording
/// on disk already carries the ones it saw. This is `posture`'s rule on
/// 2026-09-17 exactly, one structure along. See
/// `RECORD/2026-09-19.one-counting-surface.completed.md`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RefusalView {
    /// Milliseconds since the session started, the same clock every line uses.
    pub at_ms: u64,
    /// The `type` of the client message that was refused.
    pub request: String,
    pub reason: Refusal,
    /// The same thing in words. Kept rather than dropped for the count's sake:
    /// a `not_granted` tally that cannot say *which* grant is the bug report
    /// `Verdict::rule` exists to avoid being.
    pub detail: String,
}

/// A total in tokens, and every counter that produced part of it.
///
/// Every number in this system says who counted it, because two runs measured
/// differently are not comparable and nothing else would say so. A *sum* has to
/// say it harder: a session resumed onto another model keeps its turns and
/// changes its counter — which is the whole reason `retarget_header` exists —
/// so a total over such a session mixes two measurements. One entry is the
/// ordinary case; more than one means the sum mixes, and the reader is told
/// rather than left to assume it did not.
#[derive(Debug, Default, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Tokens {
    pub tokens: u32,
    /// Distinct counters that contributed, in the order first seen.
    pub counters: Vec<Counter>,
}

impl Tokens {
    fn add(&mut self, tokens: u32, counter: &Counter) {
        self.tokens += tokens;
        if !self.counters.contains(counter) {
            self.counters.push(counter.clone());
        }
    }
}

/// What one window rule took out of a session, summed over its renders.
///
/// `renders` and not `turns` is the distinction [`Divergence::renders`] draws
/// and for its reason: a rate is per render, because the render is what was
/// sent to a model. `turns` beside it is the other question — how much of the
/// conversation was touched at all — and the two differ whenever one render
/// cuts several turns, which is exactly what `Eviction::Block` does.
#[derive(Debug, Default, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Cut {
    /// Renders that cut something.
    pub renders: usize,
    /// Distinct turns named across all of them.
    pub turns: usize,
    pub tokens: Tokens,
}

/// What rule A kept out of a session.
///
/// Beside [`Cut`] and not one, because it counts a third thing the other two
/// have no equivalent of: `asking`, the renders where the *fresh* read of a
/// span was the one dropped because an older turn in the same prompt was
/// already showing it.
#[derive(Debug, Default, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Repeats {
    pub renders: usize,
    /// Distinct history turns that gave up spans.
    pub turns: usize,
    /// Renders where the turn being asked gave one up too.
    pub asking: usize,
    /// Fragments unsent, summed over the session.
    pub spans: usize,
    /// What they would have cost. **The sum of the spans**, which is
    /// deliberately not what [`Cut::tokens`] is under a prune — see
    /// [`crate::context::Repeated::tokens`], which carries the argument.
    pub tokens: Tokens,
}

/// What a session's `diverged` lines add up to.
///
/// [`TraceMessage::Diverged`] is emitted per render and says nothing about the
/// session it belongs to: a reader with a recording in front of them can see
/// that turn 6's prompt contradicted itself and cannot see whether that
/// happened once or in half the turns. **The second number is the one item 19's
/// fix waits on** — newest body wins trades measured prefix reuse for
/// truthfulness, and the trade turns on how often a window carries a path whose
/// bytes moved, which nothing counted until this.
///
/// It was a `record::divergence` over `&[RecordLine]` for one day, which is
/// where its four numbers and their reasons come from. It is here now because
/// four more findings wanted the same treatment and a `prunes()` beside a
/// `divergence()` is the per-call reporter one abstraction higher. See
/// `RECORD/2026-09-19.one-counting-surface.completed.md`.
#[derive(Debug, Default, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Divergence {
    /// Renders that carried at least one contradicted path.
    ///
    /// Not the same as `lines`: one render can contradict itself about several
    /// paths at once, and a *rate* is per render, because the render is what
    /// was sent to a model.
    pub renders: usize,
    /// Renders where at least one contradiction included the asking turn —
    /// the history disagreeing with what is on disk right now, which is the
    /// case [`TraceMessage::Diverged::asking`] exists to name.
    pub asking: usize,
    /// One entry per distinct path, in the order the session first reported it,
    /// carrying the most bodies ever sent under it in a single render.
    ///
    /// A `Vec` of pairs and not a map, for [`crate::context::Selection`]'s own
    /// reason one along: a session reports a handful of paths, the order is
    /// part of the answer, and a map would spend an allocation to save
    /// comparisons nobody can measure.
    pub paths: Vec<(String, usize)>,
    /// Every `diverged` line the session produced, which is what a reader
    /// grepping for them would count and is the number the other three are not.
    pub lines: usize,
}

/// What a session's `superseded` lines add up to: the repair, counted the way
/// [`Divergence`] counts the defect.
///
/// **Read the two together or neither means anything.** At `record::FORMAT` 15
/// a session under rule A reports supersessions and no divergences, because
/// replacing the stale body is what leaves one body to send; at 12 to 14 it
/// reports divergences and no supersessions, because the detector shipped a day
/// before the repair. So `diverged.renders` of 0 is *nothing went stale* on an
/// old stream and *everything stale was replaced* on a new one, and this
/// number is which.
///
/// It has no `asking` beside [`Divergence::asking`]: the turn being asked
/// carries the newest read of its own spans and is never the turn superseded,
/// which is the invariant [`crate::context::Superseded`] states.
#[derive(Debug, Default, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Supersession {
    /// Renders that replaced at least one stale body.
    pub renders: usize,
    /// One entry per distinct path, in the order the session first reported it,
    /// carrying how many of its spans were replaced across the session.
    pub paths: Vec<(String, usize)>,
    /// Fragments replaced, summed over the session.
    pub spans: usize,
    /// What their bytes would have cost. **The sum of the spans**, as
    /// [`Repeats::tokens`] is: what the window paid back for the citations that
    /// stand in their place is in the `history` bucket, not here.
    pub tokens: Tokens,
    /// Every `superseded` line the session produced.
    pub lines: usize,
}

/// One sandbox rule, and what it decided.
///
/// Both answers, for [`crate::sandbox::Verdict::rule`]'s own reason: *denied
/// without which rule denied is a bug report nobody can act on, and allowed
/// without which rule allowed hides the grant that was wider than someone
/// thought*. A tally that counted only denials would report the second half as
/// silence.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RuleCount {
    pub rule: String,
    pub allowed: usize,
    pub denied: usize,
}

/// What a session asked of its tools and what the sandbox said.
#[derive(Debug, Default, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Calls {
    pub total: usize,
    pub allowed: usize,
    pub denied: usize,
    /// Calls with no verdict yet — one that is still running, and one recorded
    /// without the line that carries the answer. A real state and not a zero:
    /// `total` is the other two plus this.
    pub undecided: usize,
    /// One entry per rule that decided anything, in the order first seen.
    pub rules: Vec<RuleCount>,
}

/// How often the server said no, by reason.
///
/// `not_granted` is the one this was wanted for: it is the only refusal in the
/// protocol that stops nothing and the only place a person learns the policy
/// file has a floor, and
/// `RECORD/2026-09-17.the-gate-panel-narrows.completed.md` found it being
/// cleared within a frame of arriving.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RefusalCount {
    pub reason: Refusal,
    pub count: usize,
}

/// What the gate saw, and how wide the grants were.
///
/// **`reads` and `writes` are counts of path *strings*, not of files.** Which
/// of `src/` and `src/lib.rs` is a directory is a question about a disk; the
/// sandbox answers it with `is_dir()` when it resolves a root at approval, and
/// a fold running on another machine six weeks later has no business asking. So
/// item 12 of `ROADMAP/2026-09-17` — *how often a plan grants a file rather
/// than a directory* — is taken here as far as a recording allows and no
/// further; closing it needs a field on `job_approved` written where the answer
/// is known. See `RECORD/2026-09-19.one-counting-surface.completed.md` §What is
/// rejected.
/// **Every number here changed meaning at format 16, so it says which shape it
/// counts.** Under the alternation a session closes roughly twice as many jobs
/// as it used to, because half of them are drafts, and `proposed` and
/// `declined` stop counting jobs at all — they count rounds at the gate, which
/// is where a plan that was put up and turned down now lives. A reader
/// comparing a September session against an October one would otherwise find
/// the numbers doubling and conclude the sessions got busier, which is the
/// failure [`crate::context::Supersession`]'s doc comment was written to head
/// off one structure along, given the same treatment.
#[derive(Debug, Default, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Jobs {
    /// Which shape the rest of this structure counts.
    pub shape: Shape,
    /// Jobs opened by a turn landing in them and not yet closed. At most one,
    /// under the alternation — and any number of them in a `Shape::Gated`
    /// session, where several could be approved at once.
    pub open: usize,
    pub closed: usize,
    /// Of every job, how many are drafts — objective known, plan not. Always
    /// zero under `Shape::Gated`, where a job without a plan could not exist.
    pub drafts: usize,
    /// Plans put up at the gate, however answered. **Rounds, not jobs**, under
    /// `Shape::Alternation`: a plan is offered inside a draft, so counting one
    /// here does not mean a job exists.
    pub proposed: usize,
    pub approved: usize,
    /// Rounds answered *not yet*. The number §seventh of the window-rules
    /// record kept `JobState::Rejected` in order to be able to produce, and it
    /// survives the move from a state to a round.
    pub declined: usize,
    /// Paths named as readable across every approved plan, summed.
    pub reads: usize,
    /// Paths named as writable across the same.
    pub writes: usize,
}

/// Which job model a set of counts was taken over.
///
/// Stored beside the numbers rather than left to the reader, because the
/// numbers are comparable within a shape and are not across one.
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Shape {
    /// Format 16 and up: a session opens with a draft, approving closes it and
    /// opens a plan, and every turn belongs to one of them.
    #[default]
    Alternation,
    /// Before format 16: a job was proposed, approved or refused, and the turns
    /// before the first approval belonged to nothing.
    Gated,
}

/// What a session did, added up.
///
/// **Derived, never emitted.** Every number here is arithmetic over lines the
/// session already put on the wire — which is what keeps it from drifting from
/// what it counts, on `luu export`'s own founding argument one structure along:
/// *a static mirror generated by separate code would drift, and a mirror that
/// drifts is worse than none*. A counter incremented at each site is a second
/// implementation of the finding, printed beside the finding, and believed over
/// it the day the two disagree.
///
/// It is one structure and not six for the reason that made it worth building:
/// the window rules, the divergence, the grants and the `not_granted` refusal
/// each arrived with their own per-call report and no home, and the fifth was
/// going to as well. Here a sixth finding is a field.
#[derive(Debug, Default, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Counts {
    /// Turns the session holds, evicted ones included: the transcript's length
    /// and the denominator every rate here is over. *8 of 13* is this and
    /// [`Divergence::renders`].
    pub turns: usize,
    pub evicted: Cut,
    pub pruned: Cut,
    pub repeated: Repeats,
    pub diverged: Divergence,
    pub superseded: Supersession,
    pub calls: Calls,
    /// One entry per reason that was used, in the order first seen. Empty is a
    /// session nothing was refused in — or one folded before anything kept
    /// them, which is every fold written before this.
    pub refused: Vec<RefusalCount>,
    pub jobs: Jobs,
}

/// What `GET /api/sessions` lists: enough to choose one, without its turns.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionSummary {
    pub id: String,
    pub title: String,
    pub backend: String,
    pub model: String,
    pub started_at: u64,
    pub turns: usize,
    /// Where the replayable recording lives, when there is one. The UI streams
    /// this rather than the summaries, because a summary cannot show timing.
    pub record: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionView {
    pub id: String,
    pub title: String,
    pub backend: String,
    pub model: String,
    pub started_at: u64,
    pub turns: Vec<TurnView>,
    /// In the order they were proposed. Empty for a session that ran without
    /// jobs, which is every session recorded before they existed.
    #[serde(default, alias = "tasks")]
    pub jobs: Vec<JobView>,
    /// Every plan put up at the gate and what answered it, in order.
    ///
    /// Where a proposal and a decline live under the alternation, and the only
    /// place they live: neither is a job, so neither is in `jobs`. Filled for a
    /// pre-format-16 recording too, out of its `job_proposed` and
    /// `job_rejected` lines — which is what lets the gate's numbers be read
    /// across the change even though nothing else about them survives it.
    #[serde(default)]
    pub rounds: Vec<crate::context::Round>,
    /// The record format the stream's **last** header names, when it named one.
    ///
    /// Kept because the numbers over jobs mean different things on either side
    /// of 16 and a reader needs to be told which — see [`Jobs`] and
    /// [`SessionView::shape`].
    #[serde(default)]
    pub format: Option<u32>,
    /// What this session was allowed to do, as the stream's **last** header
    /// names it — the posture its jobs were approved against.
    ///
    /// `None` is *unknown*, and specifically not `host`: a recording made
    /// before format 10 has no answer, and inventing the permissive one for it
    /// would be a number this project does not hold. A resume compares this
    /// against what the server is running and refuses the mismatch, which it
    /// could not do while the fold was dropping the field the header already
    /// carried. See
    /// `RECORD/2026-09-17.what-an-approval-was-granted-under.completed.md`.
    #[serde(default)]
    pub posture: Option<record::Posture>,
    /// The three resend rules the stream's **last** header names — what this
    /// session's turns were rendered under.
    ///
    /// `None` is *unknown* for the reason `posture` is: a recording made before
    /// format 11 has no answer, and reading the defaults back for it would be a
    /// claim the record never made. Here rather than only in the header because
    /// a resume compares the fold against what the server is about to run, and
    /// it could not compare a field the fold was dropping — which is how a
    /// posture that moved on a resume wrote no line for a day. See
    /// `RECORD/2026-09-18.the-window-rules-are-a-session-fact.completed.md` §second.
    #[serde(default)]
    pub repeat: Option<Repeat>,
    #[serde(default)]
    pub prune: Option<Prune>,
    #[serde(default)]
    pub results: Option<Results>,
    /// What this session's draft turns are told about their authority, the
    /// stream's **last** header's word on it — [`Self::repeat`]'s reason, one
    /// field along. `None` is *unknown*, format-17-or-earlier's answer, and
    /// not *no note was set*: a resume comparing the fold against a session
    /// with nothing configured needs the two to read as the same thing, which
    /// they do — both are `None`.
    #[serde(default)]
    pub authority_draft: Option<crate::sandbox::AuthorityNote>,
    /// The same, for a plan. See [`Self::authority_draft`].
    #[serde(default)]
    pub authority_plan: Option<crate::sandbox::AuthorityNote>,
    /// Everything the server declined to do, in order. Empty in a session that
    /// was refused nothing — and in every view folded before anything kept
    /// them, which the stream cannot distinguish and nothing pretends to.
    #[serde(default)]
    pub refusals: Vec<RefusalView>,
    pub record: Option<String>,
}

impl SessionView {
    pub fn new(
        id: impl Into<String>,
        backend: impl Into<String>,
        model: impl Into<String>,
    ) -> Self {
        let id = id.into();
        Self {
            title: id.clone(),
            id,
            backend: backend.into(),
            model: model.into(),
            started_at: 0,
            turns: Vec::new(),
            jobs: Vec::new(),
            rounds: Vec::new(),
            // What this binary writes. A view folded from live events never
            // meets a header, so without this the live fold and the replay of
            // the recording it is writing would disagree about the one field
            // that says how to read the rest — and `from_record` overwrites it
            // with the stream's own number the moment a header arrives.
            format: Some(record::FORMAT),
            posture: None,
            repeat: None,
            prune: None,
            results: None,
            authority_draft: None,
            authority_plan: None,
            refusals: Vec::new(),
            record: None,
        }
    }

    pub fn summary(&self) -> SessionSummary {
        SessionSummary {
            id: self.id.clone(),
            title: self.title.clone(),
            backend: self.backend.clone(),
            model: self.model.clone(),
            started_at: self.started_at,
            turns: self.turns.len(),
            record: self.record.clone(),
        }
    }

    /// What this session did, added up.
    ///
    /// Arithmetic over the fold and nothing else: no field read here was
    /// written for the sake of being counted, which is what keeps the tally
    /// from being a second opinion about its own inputs. See [`Counts`].
    pub fn counts(&self) -> Counts {
        let mut counts = Counts {
            turns: self.turns.len(),
            ..Counts::default()
        };

        for turn in &self.turns {
            if let Some(evicted) = &turn.dropped {
                counts.evicted.renders += 1;
                counts.evicted.turns += evicted.turns.len();
                counts.evicted.tokens.add(evicted.tokens, &evicted.counter);
            }
            if let Some(pruned) = &turn.cited {
                counts.pruned.renders += 1;
                counts.pruned.turns += pruned.turns.len();
                counts.pruned.tokens.add(pruned.tokens, &pruned.counter);
            }
            if let Some(repeated) = &turn.repeated {
                counts.repeated.renders += 1;
                counts.repeated.turns += repeated.turns.len();
                counts.repeated.asking += usize::from(repeated.asking);
                counts.repeated.spans += repeated.spans;
                counts
                    .repeated
                    .tokens
                    .add(repeated.tokens, &repeated.counter);
            }

            // A render and not a line, which is the distinction this whole
            // structure was shaped around: one prompt that contradicts itself
            // about three paths went out once.
            if !turn.diverged.is_empty() {
                counts.diverged.renders += 1;
                counts.diverged.lines += turn.diverged.len();
                // Counted once per render however many of its paths are
                // asking: the question is how many prompts went out
                // contradicting the disk, not how many spans did.
                if turn.diverged.iter().any(|one| one.asking) {
                    counts.diverged.asking += 1;
                }
                for one in &turn.diverged {
                    match counts
                        .diverged
                        .paths
                        .iter_mut()
                        .find(|(seen, _)| *seen == one.path)
                    {
                        Some((_, most)) => *most = (*most).max(one.bodies),
                        None => counts.diverged.paths.push((one.path.clone(), one.bodies)),
                    }
                }
            }

            // A render and not a line, for `diverged`'s reason directly above:
            // one prompt that replaced stale bodies for three paths went out
            // once.
            if !turn.superseded.is_empty() {
                counts.superseded.renders += 1;
                counts.superseded.lines += turn.superseded.len();
                for one in &turn.superseded {
                    counts.superseded.spans += one.spans;
                    counts.superseded.tokens.add(one.tokens, &one.counter);
                    match counts
                        .superseded
                        .paths
                        .iter_mut()
                        .find(|(seen, _)| *seen == one.path)
                    {
                        Some((_, spans)) => *spans += one.spans,
                        None => counts.superseded.paths.push((one.path.clone(), one.spans)),
                    }
                }
            }

            for call in &turn.tools {
                counts.calls.total += 1;
                let Some(verdict) = &call.verdict else {
                    counts.calls.undecided += 1;
                    continue;
                };
                match verdict.allowed {
                    true => counts.calls.allowed += 1,
                    false => counts.calls.denied += 1,
                }
                let rule = match counts
                    .calls
                    .rules
                    .iter_mut()
                    .find(|seen| seen.rule == verdict.rule)
                {
                    Some(seen) => seen,
                    None => {
                        counts.calls.rules.push(RuleCount {
                            rule: verdict.rule.clone(),
                            allowed: 0,
                            denied: 0,
                        });
                        counts.calls.rules.last_mut().expect("just pushed")
                    }
                };
                match verdict.allowed {
                    true => rule.allowed += 1,
                    false => rule.denied += 1,
                }
            }
        }

        for refusal in &self.refusals {
            match counts
                .refused
                .iter_mut()
                .find(|seen| seen.reason == refusal.reason)
            {
                Some(seen) => seen.count += 1,
                None => counts.refused.push(RefusalCount {
                    reason: refusal.reason,
                    count: 1,
                }),
            }
        }

        counts.jobs.shape = self.shape();
        for job in &self.jobs {
            match job.state {
                JobState::Open => counts.jobs.open += 1,
                JobState::Closed => counts.jobs.closed += 1,
            }
            if job.plan.is_none() {
                counts.jobs.drafts += 1;
            }
            // The plan as it stands, which is the approved one once there is
            // one and the proposal until then. A draft contributes nothing to
            // either, and that is the honest answer rather than a zero standing
            // in for one: a draft was never granted anything, so there is no
            // width to add.
            if let Some(plan) = &job.plan {
                counts.jobs.reads += plan.files.len();
                counts.jobs.writes += plan.writes.len();
            }
        }

        // The rounds, which is where a proposal and a decline went. A
        // `Shape::Gated` view has none and its `proposed`/`approved` are folded
        // from the job states above, so the two shapes each fill these from the
        // place their own recording put them.
        for round in &self.rounds {
            counts.jobs.proposed += 1;
            match round.answer {
                Some(crate::context::Answer::Approved { .. }) => counts.jobs.approved += 1,
                Some(crate::context::Answer::Declined) => counts.jobs.declined += 1,
                // Still on the table when the recording stopped. Counted under
                // `proposed` above and under neither answer, which is the only
                // honest place for it.
                None => {}
            }
        }

        counts
    }

    pub fn turn(&self, turn: TurnId) -> Option<&TurnView> {
        self.turns.iter().find(|t| t.turn == turn)
    }

    fn turn_mut(&mut self, turn: TurnId) -> Option<&mut TurnView> {
        self.turns.iter_mut().find(|t| t.turn == turn)
    }

    /// Which job model this view's numbers were taken over.
    ///
    /// The format number answers it, and **absent is an answer too**: the field
    /// arrived with format 16, so a stored row that has none was written by a
    /// binary from before the alternation. Reading that as the current shape
    /// would be the one mistake [`Jobs`] exists to prevent — the numbers
    /// doubling and a reader concluding the sessions got busier.
    pub fn shape(&self) -> Shape {
        match self.format {
            Some(format) if format >= 16 => Shape::Alternation,
            _ => Shape::Gated,
        }
    }

    /// Answers the plan on the table — the last round nobody has answered.
    ///
    /// By order rather than by id, because the message that answers one carries
    /// none: at most one plan is ever on the table, which is what makes the
    /// pairing unambiguous. A stream whose answer arrives with no proposal
    /// before it is a stream that lost a line, and inventing a round for it
    /// would turn a gap into a number.
    fn answer_round(&mut self, answer: crate::context::Answer) {
        if let Some(round) = self
            .rounds
            .iter_mut()
            .rev()
            .find(|round| round.answer.is_none())
        {
            round.answer = Some(answer);
        }
    }

    pub fn job(&self, job: JobId) -> Option<&JobView> {
        self.jobs.iter().find(|j| j.id == job)
    }

    fn job_mut(&mut self, job: JobId) -> Option<&mut JobView> {
        self.jobs.iter_mut().find(|j| j.id == job)
    }

    pub fn jobs(&self) -> &[JobView] {
        &self.jobs
    }

    /// Backwards compatibility accessor for callers that called `session.task`.
    pub fn task(&self, task: JobId) -> Option<&JobView> {
        self.job(task)
    }

    /// Backwards compatibility accessor for callers that called `session.tasks`.
    pub fn tasks(&self) -> &[JobView] {
        &self.jobs
    }

    /// Folds one protocol message in. `at_ms` is milliseconds since the session
    /// started, the same clock the record file uses.
    pub fn apply_protocol(&mut self, at_ms: u64, message: &ServerMessage) {
        match message {
            ServerMessage::Hello { backend, model, .. } => {
                self.backend = backend.clone();
                self.model = model.clone();
            }
            ServerMessage::TurnStarted { turn, prompt, job } => {
                if self.turn(*turn).is_none() {
                    self.turns
                        .push(TurnView::new(*turn, *job, prompt.clone(), at_ms));
                }
            }
            // Assigned and not pushed, unlike `diverged`: a turn is grounded
            // once, in one message, because the whole list is known before the
            // call that the turn is. A second one would mean a turn was asked
            // twice.
            ServerMessage::Grounded { turn, spans } => {
                if let Some(view) = self.turn_mut(*turn) {
                    view.code = spans.clone();
                }
            }
            ServerMessage::DraftOpened {
                job,
                turn,
                objective,
            } => {
                // The turn that opened it was started before the draft existed,
                // so it went out unattributed. This is where it gets its job.
                if let Some(view) = self.turn_mut(*turn) {
                    view.job = Some(*job);
                }
                if self.job(*job).is_none() {
                    self.jobs.push(JobView {
                        id: *job,
                        objective: objective.clone(),
                        plan: None,
                        proposed: None,
                        source: None,
                        state: JobState::Open,
                        summary: None,
                        closed_by: None,
                        approved_by: None,
                        replaced: None,
                    });
                }
            }
            ServerMessage::PlanProposed {
                objective,
                plan,
                source,
            } => self.rounds.push(crate::context::Round {
                objective: objective.clone(),
                plan: plan.clone(),
                source: source.unwrap_or(PlanSource::Prose),
                answer: None,
            }),
            ServerMessage::PlanDeclined => self.answer_round(crate::context::Answer::Declined),
            // A stream from before the alternation. The job it names is not one
            // under this model, so it becomes the round it always was — the
            // proposal, and whatever answered it — and no `JobView` is made.
            // `job_approved` below finds none and makes the job there, which is
            // exactly where an id is handed out now.
            ServerMessage::JobProposed {
                job: _,
                objective,
                plan,
                source,
            } => self.rounds.push(crate::context::Round {
                objective: objective.clone(),
                plan: plan.clone(),
                source: source.unwrap_or(PlanSource::Prose),
                answer: None,
            }),
            ServerMessage::Evicted {
                turn,
                turns,
                tokens,
                counter,
                policy,
            } => {
                if let Some(view) = self.turn_mut(*turn) {
                    view.dropped = Some(Evicted {
                        turns: turns.clone(),
                        tokens: *tokens,
                        counter: counter.clone(),
                        policy: *policy,
                    });
                }
                // Both halves, because a reader asks it both ways: what did
                // this turn cost the history, and is that turn still in the
                // prompt.
                for dropped in turns {
                    if let Some(view) = self.turn_mut(*dropped) {
                        view.evicted_by = Some(*turn);
                    }
                }
            }
            // Still not session state — a refusal is a thing the server
            // declined to do, and there is nothing about the session afterwards
            // that is different for it. It is kept because the clause this
            // comment used to end on came due: something wants to count them,
            // and a tally cannot count a line the fold discards. Beside the
            // turns rather than on one, because a refusal need not belong to a
            // turn: `approve_job` and `hello` are refused outside any.
            ServerMessage::Refused {
                request,
                reason,
                detail,
            } => self.refusals.push(RefusalView {
                at_ms,
                request: request.clone(),
                reason: *reason,
                detail: detail.clone(),
            }),
            ServerMessage::JobApproved {
                job,
                from: _,
                objective,
                plan,
                approved_by,
            } => {
                // Absent means the operator: every approval recorded before
                // signatures existed was one.
                let by = approved_by.clone().unwrap_or(ApprovedBy::Operator);
                let proposed = self
                    .rounds
                    .last()
                    .filter(|round| round.answer.is_none())
                    .map(|round| round.plan.clone());
                match self.job_mut(*job) {
                    // A pre-16 stream, where the job existed as a proposal
                    // before this line and this only moved it along.
                    Some(view) => {
                        view.state = JobState::Open;
                        if plan != &Plan::default() {
                            view.plan = Some(plan.clone());
                        }
                        view.approved_by = Some(by);
                    }
                    // The alternation: the approval is what hands out the id,
                    // so this line is where the job comes into existence. The
                    // draft it closed arrived as its own `job_closed` before
                    // this one, and needs nothing here.
                    None => {
                        let objective = match objective.is_empty() {
                            true => self
                                .rounds
                                .last()
                                .map(|round| round.objective.clone())
                                .unwrap_or_default(),
                            false => objective.clone(),
                        };
                        self.jobs.push(JobView {
                            id: *job,
                            objective,
                            plan: Some(plan.clone()),
                            proposed,
                            source: self.rounds.last().map(|round| round.source),
                            state: JobState::Open,
                            summary: None,
                            closed_by: None,
                            approved_by: Some(by),
                            replaced: None,
                        });
                    }
                }
                self.answer_round(crate::context::Answer::Approved { job: *job });
            }
            ServerMessage::JobClosed {
                job,
                summary,
                by,
                replaced,
            } => {
                if let Some(view) = self.job_mut(*job) {
                    view.state = JobState::Closed;
                    view.summary = Some(summary.clone());
                    view.closed_by = Some(by.unwrap_or(ClosedBy::User));
                    // Absent in a stream written before format 9, and that is
                    // not zero: a fold that saved nothing and a fold nobody
                    // measured are different claims.
                    view.replaced = replaced.clone();
                }
            }
            // Pre-16, and the same move as `job_proposed` above: the refusal
            // answers the round rather than putting a job into a state that no
            // longer exists. The `JobView` was never made, so there is none to
            // leave behind in it.
            ServerMessage::JobRejected { job: _ } => {
                self.answer_round(crate::context::Answer::Declined)
            }
            ServerMessage::JobReopened { job } => {
                if let Some(view) = self.job_mut(*job) {
                    view.state = JobState::Open;
                    view.summary = None;
                    // With the summary, and for its reason: a reopened job's
                    // turns are being sent again, so nothing has been saved.
                    view.replaced = None;
                    view.closed_by = None;
                }
            }
            ServerMessage::Token { turn, text } => {
                if let Some(view) = self.turn_mut(*turn) {
                    view.text.push_str(text);
                }
            }
            ServerMessage::Ended {
                turn,
                reason,
                usage,
            } => {
                if let Some(view) = self.turn_mut(*turn) {
                    view.reason = Some(*reason);
                    view.usage = *usage;
                    view.ended_at_ms = Some(at_ms);
                }
            }
            ServerMessage::Failed { turn, message } => {
                if let Some(view) = self.turn_mut(*turn) {
                    view.error = Some(message.clone());
                    view.ended_at_ms = Some(at_ms);
                }
            }
            ServerMessage::ToolCall {
                turn,
                step,
                name,
                arguments,
            } => {
                if let Some(view) = self.turn_mut(*turn)
                    && !view.tools.iter().any(|call| call.step == *step)
                {
                    view.tools.push(ToolCallView {
                        step: *step,
                        name: name.clone(),
                        arguments: arguments.clone(),
                        verdict: None,
                        error: None,
                        output: String::new(),
                        truncated: false,
                        duration_ms: None,
                        command: None,
                    });
                }
            }
            ServerMessage::ToolResult {
                turn,
                step,
                verdict,
                error,
                output,
                truncated,
                duration_ms,
                command,
                ..
            } => {
                if let Some(view) = self.turn_mut(*turn)
                    && let Some(call) = view.tools.iter_mut().find(|call| call.step == *step)
                {
                    call.verdict = Some(verdict.clone());
                    call.error = error.clone();
                    call.output = output.clone();
                    call.truncated = *truncated;
                    call.duration_ms = Some(*duration_ms);
                    call.command = command.clone();
                }
            }
        }
    }

    pub fn apply_trace(&mut self, _at_ms: u64, message: &TraceMessage) {
        match message {
            TraceMessage::Prompt { turn, text } => {
                if let Some(view) = self.turn_mut(*turn) {
                    view.prompt_sent = Some(text.clone());
                }
            }
            TraceMessage::Budget {
                turn,
                limit,
                counter,
                buckets,
            } => {
                if let Some(view) = self.turn_mut(*turn) {
                    view.budget = Some(Budget {
                        limit: *limit,
                        counter: counter.clone(),
                        buckets: buckets.clone(),
                    });
                }
            }
            TraceMessage::PrefixReuse {
                turn,
                shared_bytes,
                shared_tokens,
                prompt_tokens,
            } => {
                if let Some(view) = self.turn_mut(*turn) {
                    view.prefix = Some(PrefixReuse {
                        shared_bytes: *shared_bytes,
                        shared_tokens: *shared_tokens,
                        prompt_tokens: *prompt_tokens,
                    });
                }
            }
            TraceMessage::Diverged {
                turn,
                path,
                turns,
                asking,
                bodies,
            } => {
                if let Some(view) = self.turn_mut(*turn) {
                    // Pushed rather than assigned: one line per path, and a
                    // render that found three of them sends three.
                    view.diverged.push(Diverged {
                        path: path.clone(),
                        turns: turns.clone(),
                        asking: *asking,
                        bodies: *bodies,
                    });
                }
            }
            TraceMessage::Superseded {
                turn,
                path,
                turns,
                spans,
                tokens,
                counter,
            } => {
                if let Some(view) = self.turn_mut(*turn) {
                    // Pushed rather than assigned, for the line above's reason:
                    // one per path, and a render that replaced bodies for three
                    // of them sends three.
                    view.superseded.push(Superseded {
                        path: path.clone(),
                        turns: turns.clone(),
                        spans: *spans,
                        tokens: *tokens,
                        counter: counter.clone(),
                    });
                }
            }
            TraceMessage::Repeated {
                turn,
                turns,
                asking,
                spans,
                tokens,
                counter,
            } => {
                if let Some(view) = self.turn_mut(*turn) {
                    view.repeated = Some(Repeated {
                        turns: turns.clone(),
                        asking: *asking,
                        spans: *spans,
                        tokens: *tokens,
                        counter: counter.clone(),
                    });
                }
            }
            TraceMessage::Pruned {
                turn,
                turns,
                tokens,
                counter,
            } => {
                if let Some(view) = self.turn_mut(*turn) {
                    view.cited = Some(Pruned {
                        turns: turns.clone(),
                        tokens: *tokens,
                        counter: counter.clone(),
                    });
                }
                // Both halves, as eviction does it: what did this turn take out
                // of the prompt, and is that turn's code still in it.
                for pruned in turns {
                    if let Some(view) = self.turn_mut(*pruned) {
                        view.pruned_by = Some(*turn);
                    }
                }
            }
            TraceMessage::StepCall {
                turn,
                step,
                prompt_tokens,
                shared_bytes,
                shared_tokens,
                ..
            } => {
                if let Some(view) = self.turn_mut(*turn) {
                    view.extra_calls.push(ExtraCall {
                        step: *step,
                        prompt_tokens: *prompt_tokens,
                        shared_bytes: *shared_bytes,
                        shared_tokens: *shared_tokens,
                    });
                }
            }
        }
    }

    /// Rebuilds a session from a recording. The header names the backend and
    /// model, so a replayed session reports what actually produced it.
    pub fn from_record(id: impl Into<String>, lines: &[RecordLine]) -> Self {
        let mut view = Self::new(id, "", "");
        for line in lines {
            match line {
                RecordLine::Header {
                    format,
                    backend,
                    model,
                    started_at,
                    posture,
                    repeat,
                    prune,
                    results,
                    authority_draft,
                    authority_plan,
                    ..
                } => {
                    // The last header wins here too, and it is what tells a
                    // reader which job model the numbers below were taken
                    // over — see [`SessionView::shape`].
                    view.format = Some(*format);
                    view.backend = backend.clone();
                    view.model = model.clone();
                    view.started_at = *started_at;
                    // The last header wins, which is the point: a stream that
                    // gained a second one was produced somewhere else from
                    // there on, and what the session may do now is what that
                    // line says.
                    view.posture = posture.clone();
                    // And the same rule for the three beside it: a stream that
                    // gained a second header was rendered under what that line
                    // says from there on.
                    view.repeat = *repeat;
                    view.prune = *prune;
                    view.results = *results;
                    // And the two notes, one field along.
                    view.authority_draft = authority_draft.clone();
                    view.authority_plan = authority_plan.clone();
                }
                RecordLine::Protocol { at_ms, message } => view.apply_protocol(*at_ms, message),
                RecordLine::Trace { at_ms, message } => view.apply_trace(*at_ms, message),
            }
        }
        view
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::record::{self, RecordLine};

    fn lines() -> Vec<RecordLine> {
        vec![
            RecordLine::Header {
                format: record::FORMAT,
                protocol: crate::protocol::VERSION,
                backend: "mock".into(),
                model: "mock".into(),
                context_limit: Some(8192),
                counter: Some(Counter::Model { id: "mock".into() }),
                eviction: Some(crate::context::Eviction::Turn),
                posture: Some(record::Posture {
                    name: Some("container".into()),
                    runtime: "docker (luu-worker:dev)".into(),
                    enforcement: "kernel".into(),
                    network: false,
                }),
                repeat: Some(crate::context::Repeat::Always),
                prune: Some(crate::context::Prune::Never),
                results: Some(crate::context::Results::Kept),
                authority_draft: None,
                authority_plan: None,
                started_at: 1_700_000_000_000,
            },
            RecordLine::Protocol {
                at_ms: 0,
                message: ServerMessage::TurnStarted {
                    turn: 1,
                    prompt: "hola".into(),
                    job: None,
                },
            },
            RecordLine::Trace {
                at_ms: 0,
                message: TraceMessage::Prompt {
                    turn: 1,
                    text: "<|System|>\nx".into(),
                },
            },
            RecordLine::Protocol {
                at_ms: 10,
                message: ServerMessage::Token {
                    turn: 1,
                    text: "bue".into(),
                },
            },
            RecordLine::Protocol {
                at_ms: 20,
                message: ServerMessage::Token {
                    turn: 1,
                    text: "nas".into(),
                },
            },
            RecordLine::Protocol {
                at_ms: 30,
                message: ServerMessage::Ended {
                    turn: 1,
                    reason: EndReason::Stop,
                    usage: Some(Usage {
                        prompt_tokens: 5,
                        completion_tokens: 2,
                    }),
                },
            },
        ]
    }

    /// A second turn, which is the first one that can carry a prefix
    /// measurement: there is a previous prompt to measure against.
    fn second_turn() -> Vec<RecordLine> {
        vec![
            RecordLine::Protocol {
                at_ms: 40,
                message: ServerMessage::TurnStarted {
                    turn: 2,
                    prompt: "y otra".into(),
                    job: None,
                },
            },
            RecordLine::Trace {
                at_ms: 40,
                message: TraceMessage::Prompt {
                    turn: 2,
                    text: "<|System|>\nx2".into(),
                },
            },
            RecordLine::Trace {
                at_ms: 40,
                message: TraceMessage::PrefixReuse {
                    turn: 2,
                    shared_bytes: 12,
                    shared_tokens: 3,
                    prompt_tokens: 4,
                },
            },
            RecordLine::Protocol {
                at_ms: 60,
                message: ServerMessage::Ended {
                    turn: 2,
                    reason: EndReason::Stop,
                    usage: None,
                },
            },
        ]
    }

    /// A `diverged` trace reaches the turn it describes, one entry per path.
    ///
    /// The fold is where a debug client learns this: `Selection` carries the
    /// finding out of `select`, the caller puts it on the wire, and this is the
    /// step that puts it back together for a reader. See
    /// `RECORD/2026-09-19.one-path-two-bodies.completed.md`.
    #[test]
    fn a_diverged_trace_lands_on_the_turn_whose_prompt_carried_it() {
        let mut view = SessionView::from_record("completed", &lines());
        assert!(
            view.turn(1).unwrap().diverged.is_empty(),
            "a recording that says nothing leaves it empty, which is every \
             stream written before format 12",
        );

        view.apply_trace(
            40,
            &TraceMessage::Diverged {
                turn: 1,
                path: "src/lib.rs:1-4".into(),
                turns: vec![1],
                asking: true,
                bodies: 2,
            },
        );
        view.apply_trace(
            40,
            &TraceMessage::Diverged {
                turn: 1,
                path: "src/other.rs:9-20".into(),
                turns: vec![1],
                asking: false,
                bodies: 3,
            },
        );

        let turn = view.turn(1).unwrap();
        assert_eq!(turn.diverged.len(), 2, "two paths, two findings");
        assert_eq!(turn.diverged[0].path, "src/lib.rs:1-4");
        assert!(turn.diverged[0].asking);
        assert_eq!(turn.diverged[1].bodies, 3);

        // A line naming a turn the view never saw is ignored rather than
        // panicking, which is what every other arm of `apply_trace` does.
        view.apply_trace(
            40,
            &TraceMessage::Diverged {
                turn: 99,
                path: "src/gone.rs:1-2".into(),
                turns: vec![99],
                asking: false,
                bodies: 2,
            },
        );
        assert_eq!(view.turn(1).unwrap().diverged.len(), 2);
    }

    #[test]
    fn a_recording_rebuilds_the_session_it_recorded() {
        let view = SessionView::from_record("completed", &lines());
        assert_eq!(view.backend, "mock");
        assert_eq!(view.turns.len(), 1);

        let turn = view.turn(1).unwrap();
        assert_eq!(turn.text, "buenas", "tokens are assembled in order");
        assert_eq!(turn.prompt, "hola");
        assert_eq!(turn.reason, Some(EndReason::Stop));
        assert_eq!(turn.usage.unwrap().prompt_tokens, 5);
        assert_eq!(turn.ended_at_ms, Some(30));
        assert!(
            turn.prompt_sent.is_some(),
            "the trace channel's prompt is kept"
        );
        assert!(!turn.is_running());
    }

    #[test]
    fn the_first_turn_has_no_prefix_to_measure_against() {
        let view = SessionView::from_record("completed", &lines());
        assert!(
            view.turn(1).unwrap().prefix.is_none(),
            "0% on turn one would read as a cold cache rather than as no cache",
        );

        let both = [lines(), second_turn()].concat();
        let reuse = SessionView::from_record("s", &both)
            .turn(2)
            .unwrap()
            .prefix
            .unwrap();
        assert_eq!(reuse.shared_tokens, 3);
        assert_eq!(reuse.prompt_tokens, 4);
    }

    #[test]
    fn folding_live_events_gives_the_same_view_as_folding_the_record() {
        // Two turns, so every trace message the fold understands is covered:
        // the prefix measurement only exists from the second turn onwards.
        let all = [lines(), second_turn()].concat();
        let recorded = SessionView::from_record("s", &all);

        // The same messages, applied one at a time the way the server does.
        // The header's fields are the ones `serve` sets on the live view
        // itself rather than by applying a line — the posture and the three
        // resend rules included, which is why they are mirrored here instead of
        // ignored with the rest.
        let mut live = SessionView::new("s", "mock", "mock");
        live.started_at = 1_700_000_000_000;
        for line in all {
            match line {
                RecordLine::Protocol { at_ms, message } => live.apply_protocol(at_ms, &message),
                RecordLine::Trace { at_ms, message } => live.apply_trace(at_ms, &message),
                RecordLine::Header {
                    posture,
                    repeat,
                    prune,
                    results,
                    ..
                } => {
                    live.posture = posture;
                    live.repeat = repeat;
                    live.prune = prune;
                    live.results = results;
                }
            }
        }

        assert_eq!(
            serde_json::to_value(&recorded).unwrap(),
            serde_json::to_value(&live).unwrap(),
            "a static mirror must equal what the live server would serve",
        );
    }

    #[test]
    fn a_cancelled_turn_keeps_its_partial_text_and_reports_no_usage() {
        let mut view = SessionView::new("s", "mock", "mock");
        view.apply_protocol(
            0,
            &ServerMessage::TurnStarted {
                turn: 1,
                prompt: "x".into(),
                job: None,
            },
        );
        view.apply_protocol(
            5,
            &ServerMessage::Token {
                turn: 1,
                text: "par".into(),
            },
        );
        view.apply_protocol(
            9,
            &ServerMessage::Ended {
                turn: 1,
                reason: EndReason::Cancelled,
                usage: None,
            },
        );

        let turn = view.turn(1).unwrap();
        assert_eq!(turn.text, "par");
        assert_eq!(turn.reason, Some(EndReason::Cancelled));
        assert!(turn.usage.is_none());
        assert!(
            turn.budget.is_none(),
            "nothing to plot, so nothing is invented"
        );
    }

    #[test]
    fn an_eviction_marks_both_the_turn_that_cut_and_the_turns_that_left() {
        let mut view = SessionView::new("s", "mock", "mock");
        for turn in 1..=3 {
            view.apply_protocol(
                0,
                &ServerMessage::TurnStarted {
                    turn,
                    prompt: format!("q{turn}"),
                    job: None,
                },
            );
        }
        view.apply_protocol(
            9,
            &ServerMessage::Evicted {
                turn: 3,
                turns: vec![1],
                tokens: 42,
                counter: Counter::Approximate,
                policy: crate::context::Eviction::Turn,
            },
        );

        let dropped = view
            .turn(3)
            .unwrap()
            .dropped
            .clone()
            .expect("what turn 3 cut");
        assert_eq!(dropped.turns, vec![1]);
        assert_eq!(dropped.tokens, 42);
        assert_eq!(
            view.turn(1).unwrap().evicted_by,
            Some(3),
            "the turn is kept and marked: the transcript's job is the difference \
             between what happened and what the model is still shown",
        );
        assert!(
            view.turn(2).unwrap().evicted_by.is_none(),
            "still in the window",
        );
    }

    #[test]
    fn an_eviction_naming_a_turn_the_view_never_saw_is_ignored() {
        // A client that attached mid-session has turns the eviction names and
        // it does not. Marking nothing beats inventing a turn to mark.
        let mut view = SessionView::new("s", "mock", "mock");
        view.apply_protocol(
            0,
            &ServerMessage::TurnStarted {
                turn: 7,
                prompt: "q".into(),
                job: None,
            },
        );
        view.apply_protocol(
            1,
            &ServerMessage::Evicted {
                turn: 7,
                turns: vec![1, 2],
                tokens: 10,
                counter: Counter::Approximate,
                policy: crate::context::Eviction::Turn,
            },
        );

        assert_eq!(view.turns.len(), 1);
        let dropped = view.turn(7).unwrap().dropped.clone().expect("the cut");
        assert_eq!(dropped.turns, vec![1, 2]);
    }

    #[test]
    fn a_token_for_an_unknown_turn_is_ignored_rather_than_panicking() {
        let mut view = SessionView::new("s", "mock", "mock");
        view.apply_protocol(
            0,
            &ServerMessage::Token {
                turn: 9,
                text: "x".into(),
            },
        );
        assert!(view.turns.is_empty());
    }

    /// One line per path and one render per turn: the four numbers a reader of
    /// [`Divergence`] has to be able to tell apart.
    ///
    /// Two paths in one render must not count as two renders, and two `asking`
    /// paths in one render must not count as two prompts that contradicted the
    /// disk — the rate is per prompt, because the prompt is what went to a
    /// model.
    ///
    /// Moved here from `record::divergence` with its numbers unchanged, which
    /// is the point of moving it: the substrate went from `&[RecordLine]` to
    /// the fold and the answers did not.
    #[test]
    fn a_render_that_contradicts_itself_twice_is_still_one_render() {
        let mut lines = vec![header()];
        for turn in [6, 12, 13] {
            lines.push(started(turn));
        }
        lines.extend([
            diverged(6, "src/greeting.rs:1-11", 2, true),
            diverged(6, "src/tally.rs:1-6", 2, true),
            diverged(12, "src/greeting.rs:1-11", 3, true),
            diverged(13, "src/greeting.rs:1-11", 3, false),
        ]);

        let found = SessionView::from_record("s", &lines).counts().diverged;
        assert_eq!(found.lines, 4);
        assert_eq!(found.renders, 3, "three turns, four lines");
        assert_eq!(found.asking, 2, "turn 13 attached nothing");
        assert_eq!(
            found.paths,
            vec![
                ("src/greeting.rs:1-11".to_string(), 3),
                ("src/tally.rs:1-6".to_string(), 2),
            ],
            "first seen first, each carrying the most bodies it ever reached",
        );
    }

    /// A session that never edits a file it has quoted reports nothing, and the
    /// tally of nothing is zero rather than absent. The control in
    /// `scripts/tasks/edit-reread.txt` exists to produce exactly this.
    #[test]
    fn a_session_with_nothing_to_report_tallies_to_zero() {
        let quiet = vec![header(), started(1)];
        let counts = SessionView::from_record("s", &quiet).counts();
        assert_eq!(counts.diverged, Divergence::default());
        assert_eq!(counts.repeated, Repeats::default());
        assert_eq!(counts.turns, 1, "the denominator is not zero");
    }

    /// The gap the substrate move gives up, pinned rather than described.
    ///
    /// `record::divergence` counted every line in the file; the fold counts the
    /// ones that landed on a turn. Both emitters publish `TurnStarted` before
    /// any line about that turn, so the two agree in every stream this tree
    /// writes — but that is a property of two call sites and not of the format,
    /// which is why it is asserted here rather than trusted. See
    /// `RECORD/2026-09-19.one-counting-surface.completed.md` §The substrate moves.
    #[test]
    fn a_finding_about_a_turn_nobody_started_is_not_counted() {
        let orphan = vec![header(), diverged(9, "src/lib.rs:1-4", 2, true)];
        let counts = SessionView::from_record("s", &orphan).counts();
        assert_eq!(
            counts.diverged,
            Divergence::default(),
            "a finding no reader of the session can see is one nobody can act on",
        );
    }

    /// Rule A's own saving, which until format 14 was subtracted from a bucket
    /// and never reported.
    #[test]
    fn what_rule_a_kept_out_is_summed_over_the_session() {
        let mut lines = vec![header(), started(1), started(2)];
        lines.extend([
            repeated(1, &[], true, 1, 40),
            repeated(2, &[1], false, 3, 120),
        ]);

        let found = SessionView::from_record("s", &lines).counts().repeated;
        assert_eq!(found.renders, 2);
        assert_eq!(found.turns, 1, "only turn 2 named a history turn");
        assert_eq!(found.asking, 1, "turn 1's own fresh read lost one");
        assert_eq!(found.spans, 4);
        assert_eq!(found.tokens.tokens, 160);
        assert_eq!(
            found.tokens.counters,
            vec![Counter::Model { id: "mock".into() }],
            "one counter, named, because a sum has to say who measured it",
        );
    }

    /// A session resumed onto another model keeps its turns and changes its
    /// counter, so a total over it mixes two measurements. The sum still adds
    /// up; what must not happen is it adding up *silently*.
    #[test]
    fn a_total_that_mixes_counters_says_so() {
        let mut lines = vec![header(), started(1), started(2)];
        lines.push(repeated(1, &[], true, 1, 40));
        lines.push(RecordLine::Trace {
            at_ms: 2,
            message: TraceMessage::Repeated {
                turn: 2,
                turns: Vec::new(),
                asking: true,
                spans: 1,
                tokens: 60,
                counter: Counter::Approximate,
            },
        });

        let found = SessionView::from_record("s", &lines).counts().repeated;
        assert_eq!(found.tokens.tokens, 100);
        assert_eq!(
            found.tokens.counters,
            vec![Counter::Model { id: "mock".into() }, Counter::Approximate],
            "two counters in the total, in the order they contributed",
        );
    }

    /// The bill the fold wrote down for itself: refusals were dropped *until
    /// something wants to count them*, and this is that something.
    ///
    /// They are kept beside the turns rather than on one, because a refusal
    /// need not belong to a turn — `approve_job` and `hello` are refused
    /// outside any, and `not_granted` is the one this was wanted for.
    #[test]
    fn refusals_are_kept_so_that_they_can_be_counted() {
        let lines = vec![
            header(),
            refused("approve_job", Refusal::NotGranted, "src/ is not granted"),
            refused("approve_job", Refusal::NotGranted, "curl is not granted"),
            refused("prompt", Refusal::Busy, "a turn is running"),
        ];

        let view = SessionView::from_record("s", &lines);
        assert_eq!(view.refusals.len(), 3, "kept in order, detail included");
        assert_eq!(view.turns.len(), 0, "and still not session state");
        assert_eq!(
            view.counts().refused,
            vec![
                RefusalCount {
                    reason: Refusal::NotGranted,
                    count: 2
                },
                RefusalCount {
                    reason: Refusal::Busy,
                    count: 1
                },
            ],
        );
    }

    fn header() -> RecordLine {
        RecordLine::Header {
            format: record::FORMAT,
            protocol: crate::protocol::VERSION,
            backend: "mock".into(),
            model: "mock".into(),
            context_limit: Some(8192),
            counter: Some(Counter::Model { id: "mock".into() }),
            eviction: Some(crate::context::Eviction::Turn),
            posture: None,
            repeat: Some(crate::context::Repeat::Once),
            prune: Some(crate::context::Prune::Never),
            results: Some(crate::context::Results::Kept),
            authority_draft: None,
            authority_plan: None,
            started_at: 1_700_000_000_000,
        }
    }

    fn started(turn: TurnId) -> RecordLine {
        RecordLine::Protocol {
            at_ms: turn,
            message: ServerMessage::TurnStarted {
                turn,
                prompt: "hola".into(),
                job: None,
            },
        }
    }

    fn diverged(turn: TurnId, path: &str, bodies: usize, asking: bool) -> RecordLine {
        RecordLine::Trace {
            at_ms: turn,
            message: TraceMessage::Diverged {
                turn,
                path: path.into(),
                turns: Vec::new(),
                asking,
                bodies,
            },
        }
    }

    fn repeated(
        turn: TurnId,
        turns: &[TurnId],
        asking: bool,
        spans: usize,
        tokens: u32,
    ) -> RecordLine {
        RecordLine::Trace {
            at_ms: turn,
            message: TraceMessage::Repeated {
                turn,
                turns: turns.to_vec(),
                asking,
                spans,
                tokens,
                counter: Counter::Model { id: "mock".into() },
            },
        }
    }

    fn refused(request: &str, reason: Refusal, detail: &str) -> RecordLine {
        RecordLine::Protocol {
            at_ms: 1,
            message: ServerMessage::Refused {
                request: request.into(),
                reason,
                detail: detail.into(),
            },
        }
    }
}
