//! The read side: sessions and turns, as a client browses them.
//!
//! One structure, fed two ways. The live server folds events into it as they
//! happen; `luu export` folds a recorded file into it. That is deliberate — a
//! static mirror of this API that was generated by different code than the
//! server would drift, and the day it drifts it lies about the thing it exists
//! to stand in for.

use serde::{Deserialize, Serialize};

use crate::backend::Usage;
use crate::context::Counter;
use crate::protocol::{ServerMessage, TurnId};
use crate::record::RecordLine;
use crate::sandbox::Verdict;
use crate::task::{Plan, TaskId, TaskState};
use crate::trace::{Bucket, TraceMessage};
use crate::turn::EndReason;

/// How the context was spent on one turn, as we measured it before the call.
/// `usage` on the same turn is the backend's own count afterwards; the two
/// differ by the chat template we never see, and that difference is a reading,
/// not an error.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Budget {
    /// `None` when the model's window is unknown.
    pub limit: Option<u32>,
    pub counter: Counter,
    pub buckets: Vec<Bucket>,
}

/// How much of this turn's prompt the previous one already contained. `None`
/// on the first turn of a session, where there is nothing to compare against.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct PrefixReuse {
    pub shared_bytes: usize,
    pub shared_tokens: u32,
    pub prompt_tokens: u32,
}

/// One tool call as a client browses it — the "tool call timeline" panel the
/// design asks for, which is arguments, verdict, duration and result size.
///
/// The result half is optional because a call that was made and has not come
/// back yet is a real state, and a panel that waits for both would show nothing
/// while a command runs.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCallView {
    pub step: u32,
    pub name: String,
    pub arguments: serde_json::Value,
    /// Allowed or denied, and *which rule* matched — plus who enforced it.
    pub verdict: Option<Verdict>,
    pub error: Option<String>,
    pub output: String,
    pub truncated: bool,
    pub duration_ms: Option<u64>,
}

/// One task as a client browses it. The transcript groups by this and collapses
/// a closed one to its `summary` — the view collapses exactly what the context
/// collapses, which is one concept to explain instead of two.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskView {
    pub id: TaskId,
    pub plan: Plan,
    pub state: TaskState,
    /// The turns that ran inside it, in order.
    pub turns: Vec<TurnId>,
    pub summary: Option<String>,
    /// What closing it cost the history. From the trace channel, so a recording
    /// made without `--trace` has the summary and not the arithmetic.
    pub fold: Option<FoldView>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct FoldView {
    pub turns: usize,
    pub tokens_before: u32,
    pub tokens_after: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TurnView {
    pub turn: TurnId,
    /// The task it ran inside, when there was one.
    #[serde(default)]
    pub task: Option<TaskId>,
    /// What the user asked.
    pub prompt: String,
    /// What the model produced, assembled. Partial on a cancel or a failure.
    pub text: String,
    pub reason: Option<EndReason>,
    pub usage: Option<Usage>,
    pub error: Option<String>,
    /// The exact string handed to the model — the trace channel's, not a
    /// reconstruction. `None` when the turn was recorded without `--trace`.
    pub prompt_sent: Option<String>,
    pub budget: Option<Budget>,
    /// What the prompt cache could reuse of the previous turn's prompt.
    pub prefix: Option<PrefixReuse>,
    /// What the agent did during the turn, in order.
    #[serde(default)]
    pub tools: Vec<ToolCallView>,
    pub started_at_ms: u64,
    pub ended_at_ms: Option<u64>,
}

impl TurnView {
    fn new(turn: TurnId, task: Option<TaskId>, prompt: String, started_at_ms: u64) -> Self {
        Self {
            turn,
            task,
            prompt,
            text: String::new(),
            reason: None,
            usage: None,
            error: None,
            prompt_sent: None,
            budget: None,
            prefix: None,
            tools: Vec::new(),
            started_at_ms,
            ended_at_ms: None,
        }
    }

    pub fn is_running(&self) -> bool {
        self.ended_at_ms.is_none()
    }
}

/// What `GET /api/sessions` lists: enough to choose one, without its turns.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionSummary {
    pub id: String,
    pub title: String,
    pub backend: String,
    pub model: String,
    pub started_at: u64,
    pub turns: usize,
    /// Where the replayable recording lives, when there is one. The UI streams
    /// this rather than the summaries, because a summary cannot show timing.
    pub record: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionView {
    pub id: String,
    pub title: String,
    pub backend: String,
    pub model: String,
    pub started_at: u64,
    pub turns: Vec<TurnView>,
    /// In the order they were proposed, refused ones included: a plan somebody
    /// read and said no to is the most useful thing in a transcript.
    #[serde(default)]
    pub tasks: Vec<TaskView>,
    pub record: Option<String>,
}

impl SessionView {
    pub fn new(
        id: impl Into<String>,
        backend: impl Into<String>,
        model: impl Into<String>,
    ) -> Self {
        let id = id.into();
        Self {
            title: id.clone(),
            id,
            backend: backend.into(),
            model: model.into(),
            started_at: 0,
            turns: Vec::new(),
            tasks: Vec::new(),
            record: None,
        }
    }

    pub fn summary(&self) -> SessionSummary {
        SessionSummary {
            id: self.id.clone(),
            title: self.title.clone(),
            backend: self.backend.clone(),
            model: self.model.clone(),
            started_at: self.started_at,
            turns: self.turns.len(),
            record: self.record.clone(),
        }
    }

    pub fn turn(&self, turn: TurnId) -> Option<&TurnView> {
        self.turns.iter().find(|t| t.turn == turn)
    }

    fn turn_mut(&mut self, turn: TurnId) -> Option<&mut TurnView> {
        self.turns.iter_mut().find(|t| t.turn == turn)
    }

    pub fn task(&self, task: TaskId) -> Option<&TaskView> {
        self.tasks.iter().find(|t| t.id == task)
    }

    fn task_mut(&mut self, task: TaskId) -> Option<&mut TaskView> {
        self.tasks.iter_mut().find(|t| t.id == task)
    }

    /// Folds one protocol message in. `at_ms` is milliseconds since the session
    /// started, the same clock the record file uses.
    pub fn apply_protocol(&mut self, at_ms: u64, message: &ServerMessage) {
        match message {
            ServerMessage::Hello { backend, model, .. } => {
                self.backend = backend.clone();
                self.model = model.clone();
            }
            ServerMessage::TurnStarted { turn, prompt, task } => {
                if self.turn(*turn).is_none() {
                    self.turns
                        .push(TurnView::new(*turn, *task, prompt.clone(), at_ms));
                    if let Some(view) = task.and_then(|task| self.task_mut(task)) {
                        view.turns.push(*turn);
                    }
                }
            }
            ServerMessage::TaskProposed { task, plan } => {
                if self.task(*task).is_none() {
                    self.tasks.push(TaskView {
                        id: *task,
                        plan: plan.clone(),
                        state: TaskState::Proposed,
                        turns: Vec::new(),
                        summary: None,
                        fold: None,
                    });
                }
            }
            ServerMessage::TaskApproved { task } => {
                if let Some(view) = self.task_mut(*task) {
                    view.state = TaskState::Approved;
                }
            }
            ServerMessage::TaskDiscarded { task } => {
                if let Some(view) = self.task_mut(*task) {
                    view.state = TaskState::Discarded;
                }
            }
            ServerMessage::TaskClosed { task, summary } => {
                if let Some(view) = self.task_mut(*task) {
                    view.state = TaskState::Closed;
                    view.summary = Some(summary.clone());
                }
            }
            // A refusal is addressed to the client that asked, and it is
            // nothing that happened to the session. Nothing to fold.
            ServerMessage::Refused { .. } => {}
            ServerMessage::Token { turn, text } => {
                if let Some(view) = self.turn_mut(*turn) {
                    view.text.push_str(text);
                }
            }
            ServerMessage::Ended {
                turn,
                reason,
                usage,
            } => {
                if let Some(view) = self.turn_mut(*turn) {
                    view.reason = Some(*reason);
                    view.usage = *usage;
                    view.ended_at_ms = Some(at_ms);
                }
            }
            ServerMessage::Failed { turn, message } => {
                if let Some(view) = self.turn_mut(*turn) {
                    view.error = Some(message.clone());
                    view.ended_at_ms = Some(at_ms);
                }
            }
            ServerMessage::ToolCall {
                turn,
                step,
                name,
                arguments,
            } => {
                if let Some(view) = self.turn_mut(*turn)
                    && !view.tools.iter().any(|call| call.step == *step)
                {
                    view.tools.push(ToolCallView {
                        step: *step,
                        name: name.clone(),
                        arguments: arguments.clone(),
                        verdict: None,
                        error: None,
                        output: String::new(),
                        truncated: false,
                        duration_ms: None,
                    });
                }
            }
            ServerMessage::ToolResult {
                turn,
                step,
                verdict,
                error,
                output,
                truncated,
                duration_ms,
                ..
            } => {
                if let Some(view) = self.turn_mut(*turn)
                    && let Some(call) = view.tools.iter_mut().find(|call| call.step == *step)
                {
                    call.verdict = Some(verdict.clone());
                    call.error = error.clone();
                    call.output = output.clone();
                    call.truncated = *truncated;
                    call.duration_ms = Some(*duration_ms);
                }
            }
        }
    }

    pub fn apply_trace(&mut self, _at_ms: u64, message: &TraceMessage) {
        match message {
            TraceMessage::TaskFolded {
                task,
                turns,
                tokens_before,
                tokens_after,
            } => {
                if let Some(view) = self.task_mut(*task) {
                    view.fold = Some(FoldView {
                        turns: *turns,
                        tokens_before: *tokens_before,
                        tokens_after: *tokens_after,
                    });
                }
            }
            TraceMessage::Prompt { turn, text } => {
                if let Some(view) = self.turn_mut(*turn) {
                    view.prompt_sent = Some(text.clone());
                }
            }
            TraceMessage::Budget {
                turn,
                limit,
                counter,
                buckets,
            } => {
                if let Some(view) = self.turn_mut(*turn) {
                    view.budget = Some(Budget {
                        limit: *limit,
                        counter: counter.clone(),
                        buckets: buckets.clone(),
                    });
                }
            }
            TraceMessage::PrefixReuse {
                turn,
                shared_bytes,
                shared_tokens,
                prompt_tokens,
            } => {
                if let Some(view) = self.turn_mut(*turn) {
                    view.prefix = Some(PrefixReuse {
                        shared_bytes: *shared_bytes,
                        shared_tokens: *shared_tokens,
                        prompt_tokens: *prompt_tokens,
                    });
                }
            }
        }
    }

    /// Rebuilds a session from a recording. The header names the backend and
    /// model, so a replayed session reports what actually produced it.
    pub fn from_record(id: impl Into<String>, lines: &[RecordLine]) -> Self {
        let mut view = Self::new(id, "", "");
        for line in lines {
            match line {
                RecordLine::Header {
                    backend,
                    model,
                    started_at,
                    ..
                } => {
                    view.backend = backend.clone();
                    view.model = model.clone();
                    view.started_at = *started_at;
                }
                RecordLine::Protocol { at_ms, message } => view.apply_protocol(*at_ms, message),
                RecordLine::Trace { at_ms, message } => view.apply_trace(*at_ms, message),
            }
        }
        view
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::record::{self, RecordLine};

    fn lines() -> Vec<RecordLine> {
        vec![
            RecordLine::Header {
                format: record::FORMAT,
                protocol: crate::protocol::VERSION,
                backend: "mock".into(),
                model: "mock".into(),
                context_limit: Some(8192),
                counter: Some(Counter::Model { id: "mock".into() }),
                eviction: Some(crate::context::Eviction::Turn),
                started_at: 1_700_000_000_000,
            },
            RecordLine::Protocol {
                at_ms: 0,
                message: ServerMessage::TurnStarted {
                    turn: 1,
                    prompt: "hola".into(),
                    task: None,
                },
            },
            RecordLine::Trace {
                at_ms: 0,
                message: TraceMessage::Prompt {
                    turn: 1,
                    text: "<|System|>\nx".into(),
                },
            },
            RecordLine::Protocol {
                at_ms: 10,
                message: ServerMessage::Token {
                    turn: 1,
                    text: "bue".into(),
                },
            },
            RecordLine::Protocol {
                at_ms: 20,
                message: ServerMessage::Token {
                    turn: 1,
                    text: "nas".into(),
                },
            },
            RecordLine::Protocol {
                at_ms: 30,
                message: ServerMessage::Ended {
                    turn: 1,
                    reason: EndReason::Stop,
                    usage: Some(Usage {
                        prompt_tokens: 5,
                        completion_tokens: 2,
                    }),
                },
            },
        ]
    }

    /// A second turn, which is the first one that can carry a prefix
    /// measurement: there is a previous prompt to measure against.
    fn second_turn() -> Vec<RecordLine> {
        vec![
            RecordLine::Protocol {
                at_ms: 40,
                message: ServerMessage::TurnStarted {
                    turn: 2,
                    prompt: "y otra".into(),
                    task: None,
                },
            },
            RecordLine::Trace {
                at_ms: 40,
                message: TraceMessage::Prompt {
                    turn: 2,
                    text: "<|System|>\nx2".into(),
                },
            },
            RecordLine::Trace {
                at_ms: 40,
                message: TraceMessage::PrefixReuse {
                    turn: 2,
                    shared_bytes: 12,
                    shared_tokens: 3,
                    prompt_tokens: 4,
                },
            },
            RecordLine::Protocol {
                at_ms: 60,
                message: ServerMessage::Ended {
                    turn: 2,
                    reason: EndReason::Stop,
                    usage: None,
                },
            },
        ]
    }

    #[test]
    fn a_recording_rebuilds_the_session_it_recorded() {
        let view = SessionView::from_record("completed", &lines());
        assert_eq!(view.backend, "mock");
        assert_eq!(view.turns.len(), 1);

        let turn = view.turn(1).unwrap();
        assert_eq!(turn.text, "buenas", "tokens are assembled in order");
        assert_eq!(turn.prompt, "hola");
        assert_eq!(turn.reason, Some(EndReason::Stop));
        assert_eq!(turn.usage.unwrap().prompt_tokens, 5);
        assert_eq!(turn.ended_at_ms, Some(30));
        assert!(
            turn.prompt_sent.is_some(),
            "the trace channel's prompt is kept"
        );
        assert!(!turn.is_running());
    }

    #[test]
    fn the_first_turn_has_no_prefix_to_measure_against() {
        let view = SessionView::from_record("completed", &lines());
        assert!(
            view.turn(1).unwrap().prefix.is_none(),
            "0% on turn one would read as a cold cache rather than as no cache",
        );

        let both = [lines(), second_turn()].concat();
        let reuse = SessionView::from_record("s", &both)
            .turn(2)
            .unwrap()
            .prefix
            .unwrap();
        assert_eq!(reuse.shared_tokens, 3);
        assert_eq!(reuse.prompt_tokens, 4);
    }

    /// A task around the second turn: proposed, approved, closed. The lifecycle
    /// is on the protocol channel and what the fold cost is on the trace one,
    /// so a recording of it exercises both.
    fn task_lines() -> Vec<RecordLine> {
        let plan = crate::task::Plan::from_reply(
            "read the file",
            "```plan\n{\"steps\":[\"read it\"],\"paths\":[\"AGENTS.md\"]}\n```",
        );
        vec![
            RecordLine::Protocol {
                at_ms: 35,
                message: ServerMessage::TaskProposed { task: 1, plan },
            },
            RecordLine::Protocol {
                at_ms: 36,
                message: ServerMessage::TaskApproved { task: 1 },
            },
            RecordLine::Protocol {
                at_ms: 70,
                message: ServerMessage::TaskClosed {
                    task: 1,
                    summary: "[task 1] read the file — closed".into(),
                },
            },
            RecordLine::Trace {
                at_ms: 70,
                message: TraceMessage::TaskFolded {
                    task: 1,
                    turns: 2,
                    tokens_before: 90,
                    tokens_after: 30,
                },
            },
        ]
    }

    #[test]
    fn a_task_collects_the_turns_that_ran_inside_it() {
        let mut second = second_turn();
        // The turn the task owns says so itself, rather than the client
        // guessing from what happened to be open when it folded the record.
        if let RecordLine::Protocol {
            message: ServerMessage::TurnStarted { task, .. },
            ..
        } = &mut second[0]
        {
            *task = Some(1);
        }
        let all = [
            lines(),
            task_lines()[..2].to_vec(),
            second,
            task_lines()[2..].to_vec(),
        ]
        .concat();

        let view = SessionView::from_record("s", &all);
        let task = view.task(1).unwrap();
        assert_eq!(task.state, TaskState::Closed);
        assert_eq!(task.turns, [2], "turn 1 ran before the task existed");
        assert_eq!(task.plan.steps, ["read it"]);
        assert!(task.summary.is_some());
        assert_eq!(
            task.fold.unwrap().tokens_after,
            30,
            "what the one rewrite in the session cost is part of the reading",
        );
        assert_eq!(view.turn(1).unwrap().task, None);
        assert_eq!(view.turn(2).unwrap().task, Some(1));
    }

    #[test]
    fn folding_live_events_gives_the_same_view_as_folding_the_record() {
        // Two turns, so every trace message the fold understands is covered:
        // the prefix measurement only exists from the second turn onwards.
        let all = [lines(), second_turn(), task_lines()].concat();
        let recorded = SessionView::from_record("s", &all);

        // The same messages, applied one at a time the way the server does.
        let mut live = SessionView::new("s", "mock", "mock");
        live.started_at = 1_700_000_000_000;
        for line in all {
            match line {
                RecordLine::Protocol { at_ms, message } => live.apply_protocol(at_ms, &message),
                RecordLine::Trace { at_ms, message } => live.apply_trace(at_ms, &message),
                RecordLine::Header { .. } => {}
            }
        }

        assert_eq!(
            serde_json::to_value(&recorded).unwrap(),
            serde_json::to_value(&live).unwrap(),
            "a static mirror must equal what the live server would serve",
        );
    }

    #[test]
    fn a_cancelled_turn_keeps_its_partial_text_and_reports_no_usage() {
        let mut view = SessionView::new("s", "mock", "mock");
        view.apply_protocol(
            0,
            &ServerMessage::TurnStarted {
                turn: 1,
                prompt: "x".into(),
                task: None,
            },
        );
        view.apply_protocol(
            5,
            &ServerMessage::Token {
                turn: 1,
                text: "par".into(),
            },
        );
        view.apply_protocol(
            9,
            &ServerMessage::Ended {
                turn: 1,
                reason: EndReason::Cancelled,
                usage: None,
            },
        );

        let turn = view.turn(1).unwrap();
        assert_eq!(turn.text, "par");
        assert_eq!(turn.reason, Some(EndReason::Cancelled));
        assert!(turn.usage.is_none());
        assert!(
            turn.budget.is_none(),
            "nothing to plot, so nothing is invented"
        );
    }

    #[test]
    fn a_token_for_an_unknown_turn_is_ignored_rather_than_panicking() {
        let mut view = SessionView::new("s", "mock", "mock");
        view.apply_protocol(
            0,
            &ServerMessage::Token {
                turn: 9,
                text: "x".into(),
            },
        );
        assert!(view.turns.is_empty());
    }
}
