//! The read side: sessions and turns, as a client browses them.
//!
//! One structure, fed two ways. The live server folds events into it as they
//! happen; `luu export` folds a recorded file into it. That is deliberate — a
//! static mirror of this API that was generated by different code than the
//! server would drift, and the day it drifts it lies about the thing it exists
//! to stand in for.

use serde::{Deserialize, Serialize};

use crate::backend::Usage;
use crate::context::Counter;
use crate::protocol::{ServerMessage, TurnId};
use crate::record::RecordLine;
use crate::trace::{Bucket, TraceMessage};
use crate::turn::EndReason;

/// How the context was spent on one turn, as we measured it before the call.
/// `usage` on the same turn is the backend's own count afterwards; the two
/// differ by the chat template we never see, and that difference is a reading,
/// not an error.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Budget {
    /// `None` when the model's window is unknown.
    pub limit: Option<u32>,
    pub counter: Counter,
    pub buckets: Vec<Bucket>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TurnView {
    pub turn: TurnId,
    /// What the user asked.
    pub prompt: String,
    /// What the model produced, assembled. Partial on a cancel or a failure.
    pub text: String,
    pub reason: Option<EndReason>,
    pub usage: Option<Usage>,
    pub error: Option<String>,
    /// The exact string handed to the model — the trace channel's, not a
    /// reconstruction. `None` when the turn was recorded without `--trace`.
    pub prompt_sent: Option<String>,
    pub budget: Option<Budget>,
    pub started_at_ms: u64,
    pub ended_at_ms: Option<u64>,
}

impl TurnView {
    fn new(turn: TurnId, prompt: String, started_at_ms: u64) -> Self {
        Self {
            turn,
            prompt,
            text: String::new(),
            reason: None,
            usage: None,
            error: None,
            prompt_sent: None,
            budget: None,
            started_at_ms,
            ended_at_ms: None,
        }
    }

    pub fn is_running(&self) -> bool {
        self.ended_at_ms.is_none()
    }
}

/// What `GET /api/sessions` lists: enough to choose one, without its turns.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionSummary {
    pub id: String,
    pub title: String,
    pub backend: String,
    pub model: String,
    pub started_at: u64,
    pub turns: usize,
    /// Where the replayable recording lives, when there is one. The UI streams
    /// this rather than the summaries, because a summary cannot show timing.
    pub record: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionView {
    pub id: String,
    pub title: String,
    pub backend: String,
    pub model: String,
    pub started_at: u64,
    pub turns: Vec<TurnView>,
    pub record: Option<String>,
}

impl SessionView {
    pub fn new(
        id: impl Into<String>,
        backend: impl Into<String>,
        model: impl Into<String>,
    ) -> Self {
        let id = id.into();
        Self {
            title: id.clone(),
            id,
            backend: backend.into(),
            model: model.into(),
            started_at: 0,
            turns: Vec::new(),
            record: None,
        }
    }

    pub fn summary(&self) -> SessionSummary {
        SessionSummary {
            id: self.id.clone(),
            title: self.title.clone(),
            backend: self.backend.clone(),
            model: self.model.clone(),
            started_at: self.started_at,
            turns: self.turns.len(),
            record: self.record.clone(),
        }
    }

    pub fn turn(&self, turn: TurnId) -> Option<&TurnView> {
        self.turns.iter().find(|t| t.turn == turn)
    }

    fn turn_mut(&mut self, turn: TurnId) -> Option<&mut TurnView> {
        self.turns.iter_mut().find(|t| t.turn == turn)
    }

    /// Folds one protocol message in. `at_ms` is milliseconds since the session
    /// started, the same clock the record file uses.
    pub fn apply_protocol(&mut self, at_ms: u64, message: &ServerMessage) {
        match message {
            ServerMessage::Hello { backend, model, .. } => {
                self.backend = backend.clone();
                self.model = model.clone();
            }
            ServerMessage::TurnStarted { turn, prompt } => {
                if self.turn(*turn).is_none() {
                    self.turns.push(TurnView::new(*turn, prompt.clone(), at_ms));
                }
            }
            ServerMessage::Token { turn, text } => {
                if let Some(view) = self.turn_mut(*turn) {
                    view.text.push_str(text);
                }
            }
            ServerMessage::Ended {
                turn,
                reason,
                usage,
            } => {
                if let Some(view) = self.turn_mut(*turn) {
                    view.reason = Some(*reason);
                    view.usage = *usage;
                    view.ended_at_ms = Some(at_ms);
                }
            }
            ServerMessage::Failed { turn, message } => {
                if let Some(view) = self.turn_mut(*turn) {
                    view.error = Some(message.clone());
                    view.ended_at_ms = Some(at_ms);
                }
            }
        }
    }

    pub fn apply_trace(&mut self, _at_ms: u64, message: &TraceMessage) {
        match message {
            TraceMessage::Prompt { turn, text } => {
                if let Some(view) = self.turn_mut(*turn) {
                    view.prompt_sent = Some(text.clone());
                }
            }
            TraceMessage::Budget {
                turn,
                limit,
                counter,
                buckets,
            } => {
                if let Some(view) = self.turn_mut(*turn) {
                    view.budget = Some(Budget {
                        limit: *limit,
                        counter: counter.clone(),
                        buckets: buckets.clone(),
                    });
                }
            }
        }
    }

    /// Rebuilds a session from a recording. The header names the backend and
    /// model, so a replayed session reports what actually produced it.
    pub fn from_record(id: impl Into<String>, lines: &[RecordLine]) -> Self {
        let mut view = Self::new(id, "", "");
        for line in lines {
            match line {
                RecordLine::Header {
                    backend,
                    model,
                    started_at,
                    ..
                } => {
                    view.backend = backend.clone();
                    view.model = model.clone();
                    view.started_at = *started_at;
                }
                RecordLine::Protocol { at_ms, message } => view.apply_protocol(*at_ms, message),
                RecordLine::Trace { at_ms, message } => view.apply_trace(*at_ms, message),
            }
        }
        view
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::record::{self, RecordLine};

    fn lines() -> Vec<RecordLine> {
        vec![
            RecordLine::Header {
                format: record::FORMAT,
                protocol: crate::protocol::VERSION,
                backend: "mock".into(),
                model: "mock".into(),
                context_limit: Some(8192),
                counter: Some(Counter::Model { id: "mock".into() }),
                started_at: 1_700_000_000_000,
            },
            RecordLine::Protocol {
                at_ms: 0,
                message: ServerMessage::TurnStarted {
                    turn: 1,
                    prompt: "hola".into(),
                },
            },
            RecordLine::Trace {
                at_ms: 0,
                message: TraceMessage::Prompt {
                    turn: 1,
                    text: "<|System|>\nx".into(),
                },
            },
            RecordLine::Protocol {
                at_ms: 10,
                message: ServerMessage::Token {
                    turn: 1,
                    text: "bue".into(),
                },
            },
            RecordLine::Protocol {
                at_ms: 20,
                message: ServerMessage::Token {
                    turn: 1,
                    text: "nas".into(),
                },
            },
            RecordLine::Protocol {
                at_ms: 30,
                message: ServerMessage::Ended {
                    turn: 1,
                    reason: EndReason::Stop,
                    usage: Some(Usage {
                        prompt_tokens: 5,
                        completion_tokens: 2,
                    }),
                },
            },
        ]
    }

    #[test]
    fn a_recording_rebuilds_the_session_it_recorded() {
        let view = SessionView::from_record("completed", &lines());
        assert_eq!(view.backend, "mock");
        assert_eq!(view.turns.len(), 1);

        let turn = view.turn(1).unwrap();
        assert_eq!(turn.text, "buenas", "tokens are assembled in order");
        assert_eq!(turn.prompt, "hola");
        assert_eq!(turn.reason, Some(EndReason::Stop));
        assert_eq!(turn.usage.unwrap().prompt_tokens, 5);
        assert_eq!(turn.ended_at_ms, Some(30));
        assert!(
            turn.prompt_sent.is_some(),
            "the trace channel's prompt is kept"
        );
        assert!(!turn.is_running());
    }

    #[test]
    fn folding_live_events_gives_the_same_view_as_folding_the_record() {
        let recorded = SessionView::from_record("s", &lines());

        // The same messages, applied one at a time the way the server does.
        let mut live = SessionView::new("s", "mock", "mock");
        live.started_at = 1_700_000_000_000;
        for line in lines() {
            match line {
                RecordLine::Protocol { at_ms, message } => live.apply_protocol(at_ms, &message),
                RecordLine::Trace { at_ms, message } => live.apply_trace(at_ms, &message),
                RecordLine::Header { .. } => {}
            }
        }

        assert_eq!(
            serde_json::to_value(&recorded).unwrap(),
            serde_json::to_value(&live).unwrap(),
            "a static mirror must equal what the live server would serve",
        );
    }

    #[test]
    fn a_cancelled_turn_keeps_its_partial_text_and_reports_no_usage() {
        let mut view = SessionView::new("s", "mock", "mock");
        view.apply_protocol(
            0,
            &ServerMessage::TurnStarted {
                turn: 1,
                prompt: "x".into(),
            },
        );
        view.apply_protocol(
            5,
            &ServerMessage::Token {
                turn: 1,
                text: "par".into(),
            },
        );
        view.apply_protocol(
            9,
            &ServerMessage::Ended {
                turn: 1,
                reason: EndReason::Cancelled,
                usage: None,
            },
        );

        let turn = view.turn(1).unwrap();
        assert_eq!(turn.text, "par");
        assert_eq!(turn.reason, Some(EndReason::Cancelled));
        assert!(turn.usage.is_none());
        assert!(
            turn.budget.is_none(),
            "nothing to plot, so nothing is invented"
        );
    }

    #[test]
    fn a_token_for_an_unknown_turn_is_ignored_rather_than_panicking() {
        let mut view = SessionView::new("s", "mock", "mock");
        view.apply_protocol(
            0,
            &ServerMessage::Token {
                turn: 9,
                text: "x".into(),
            },
        );
        assert!(view.turns.is_empty());
    }
}
