//! `luu export` — a recording, written out as the static twin of the live API.
//!
//! GitHub Pages has no server behind it, so the read side has to exist as
//! files. What makes that safe is that these files are produced by folding the
//! recording through [`SessionView`] — the same structure, and the same fold,
//! the live server uses. A static mirror generated by separate code would drift,
//! and a mirror that drifts is worse than none.
//!
//! Every path ends in `.json`, because a static host cannot serve
//! `…/turns` as JSON. The live server answers both spellings, so a client uses
//! one set of URLs against either.

use std::path::{Path, PathBuf};

use agent_core::api::{SessionSummary, SessionView};
use agent_core::record::RecordLine;
use anyhow::{Context, Result};
use serde::Serialize;

pub struct Session {
    /// The id the session is served under, taken from the file stem.
    pub id: String,
    pub record: RecordSource,
    pub lines: Vec<RecordLine>,
}

pub struct RecordSource {
    /// How the page should reach the recording, relative to the site root.
    pub url: String,
}

fn write_json<T: Serialize>(path: &Path, value: &T) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
    }
    let json = serde_json::to_string_pretty(value)?;
    std::fs::write(path, format!("{json}\n"))
        .with_context(|| format!("writing {}", path.display()))?;
    Ok(())
}

/// Reads a `.jsonl` recording. A malformed line fails the export rather than
/// being skipped: a fixture with a hole in it is the kind of thing that gets
/// noticed months later, by which time it looks like a server bug.
pub fn read_record(path: &Path) -> Result<Vec<RecordLine>> {
    let text =
        std::fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;

    text.lines()
        .enumerate()
        .filter(|(_, line)| !line.trim().is_empty())
        .map(|(n, line)| {
            serde_json::from_str::<RecordLine>(line)
                .with_context(|| format!("{}:{}", path.display(), n + 1))
        })
        .collect()
}

/// Writes the whole tree for a set of recordings.
pub fn export(sessions: &[Session], out: &Path) -> Result<Vec<SessionSummary>> {
    let mut summaries = Vec::new();

    for session in sessions {
        let mut view = SessionView::from_record(&session.id, &session.lines);
        view.record = Some(session.record.url.clone());
        view.title = title_for(&session.id);

        let root: PathBuf = out.join("sessions").join(&session.id);
        write_json(
            &out.join("sessions").join(format!("{}.json", session.id)),
            &view,
        )?;
        write_json(&root.join("turns.json"), &view.turns)?;
        write_json(
            &root.join("context.json"),
            &serde_json::json!({
                "turn": view.turns.iter().rev().find(|t| t.budget.is_some()).map(|t| t.turn),
                "budget": view.turns.iter().rev().find_map(|t| t.budget.clone()),
            }),
        )?;

        for turn in &view.turns {
            let turns = root.join("turns");
            write_json(&turns.join(format!("{}.json", turn.turn)), turn)?;
            write_json(
                &turns.join(turn.turn.to_string()).join("prompt.json"),
                &serde_json::json!({ "turn": turn.turn, "text": turn.prompt_sent }),
            )?;
        }

        summaries.push(view.summary());
    }

    write_json(&out.join("sessions.json"), &summaries)?;
    Ok(summaries)
}

/// `backend-failure` reads better in a picker than `backend_failure` does.
fn title_for(id: &str) -> String {
    let words = id.replace(['-', '_'], " ");
    let mut chars = words.chars();
    match chars.next() {
        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
        None => words,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ids_become_readable_titles() {
        assert_eq!(title_for("backend-failure"), "Backend failure");
        assert_eq!(title_for("completed"), "Completed");
    }

    #[test]
    fn a_malformed_line_fails_the_export_instead_of_being_skipped() {
        let dir = std::env::temp_dir().join("luu-export-test");
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("broken.jsonl");
        std::fs::write(&path, "{\"channel\":\"header\"}\nnot json\n").unwrap();

        let error = read_record(&path).unwrap_err().to_string();
        assert!(
            error.contains("broken.jsonl:1"),
            "the failing line is named: {error}"
        );
    }
}
